[Nacos]
Env = dev
#应用ID
AppID = msgPushSite
#命名空间Id
NamespaceId = Api
#服务端的API鉴权Username
Username = dev
#服务端的API鉴权Password
Password = rmb2VNC3hnt@vbt-jxb
#Nacos地址
Address = nacos.u1s1.biz
#端口号
Port = 8848
#协议
Scheme = http
#缓存service信息的目录，默认是当前运行目录
CacheDir = ./nacos
#日志存储路径
LogDir = ./nacos



